### ISSUE TITLE
random event: [ERROR] Couldn't compile app

### ISSUE THREAD

**Issue by ibinti** [bugvm/bugvm#33]
[ERROR] Couldn't compile app
java.lang.NullPointerException
    at com.bugvm.compiler.Linker.link(Linker.java:205)
    at com.bugvm.compiler.AppCompiler.compile(AppCompiler.java:464)
    at com.bugvm.compiler.AppCompiler.build(AppCompiler.java:767)
    at com.bugvm.idea.compilation.BugVmCompilerThread.doCompile(BugVmCompilerThread.java:60)
    at com.bugvm.idea.compilation.BugVmCompilerThread.run(BugVmCompilerThread.java:66)

**Comment by ibinti** [comment]
now you see, now you don't
