### ISSUE TITLE
Can't run on device

### ISSUE THREAD

**Issue by igorushko** [bugvm/bugvm#46]
I can't run on device in idea, android studio, and bugvm studio

For clear experiment i create new project on gdx-setup.jar and replace config

I do this:
1 connect iphone
2 create bugvm project config
![image](https://cloud.githubusercontent.com/assets/9007174/14683438/5f7b7538-0733-11e6-8ee5-67c35cca1c02.png)
3 push green triangle to run

On first compile i get this error
`[ERROR] Couldn't start application
java.lang.UnsatisfiedLinkError: /Users/ushkoigor/Library/Caches/BugVMStudio1.0/tmp/libbugvm-libimobiledevice608653038196383825.dylib: dlopen(/Users/ushkoigor/Library/Caches/BugVMStudio1.0/tmp/libbugvm-libimobiledevice608653038196383825.dylib, 1): Library not loaded: /usr/local/opt/gnutls/lib/libgnutls.28.dylib
  Referenced from: /Users/ushkoigor/Library/Caches/BugVMStudio1.0/tmp/libbugvm-libimobiledevice608653038196383825.dylib
  Reason: image not found
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.Runtime.load(Runtime.java:797)
    at com.bugvm.libimobiledevice.NativeLibrary.load(NativeLibrary.java:90)
    at com.bugvm.libimobiledevice.binding.LibIMobileDeviceJNI.<clinit>(LibIMobileDeviceJNI.java:191)
    at com.bugvm.libimobiledevice.binding.StringArrayOut.<init>(StringArrayOut.java:44)
    at com.bugvm.libimobiledevice.IDevice.listUdids(IDevice.java:136)
    at com.bugvm.compiler.target.ios.IOSTarget.createIOSDevLauncher(IOSTarget.java:262)
    at com.bugvm.compiler.target.ios.IOSTarget.createLauncher(IOSTarget.java:152)
    at com.bugvm.compiler.target.AbstractTarget.doLaunch(AbstractTarget.java:490)
    at com.bugvm.compiler.target.ios.IOSTarget.doLaunch(IOSTarget.java:602)
    at com.bugvm.compiler.target.AbstractTarget.launch(AbstractTarget.java:486)
    at com.bugvm.compiler.AppCompiler.launchAsync(AppCompiler.java:827)
    at com.bugvm.idea.running.BugVmRunProfileState.executeRun(BugVmRunProfileState.java:65)
    at com.bugvm.idea.running.BugVmRunProfileState.startProcess(BugVmRunProfileState.java:109)
    at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
    at com.bugvm.idea.running.BugVmRunner.doExecute(BugVmRunner.java:79)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
    at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:367)
    at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:144)
    at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:334)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:662)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:397)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

[WARNING] warning: no debug symbols in executable (-arch armv7)`

But next time i get
`[ERROR] Couldn't start application
java.lang.NoClassDefFoundError: Could not initialize class com.bugvm.libimobiledevice.binding.LibIMobileDeviceJNI
    at com.bugvm.libimobiledevice.binding.StringArrayOut.<init>(StringArrayOut.java:44)
    at com.bugvm.libimobiledevice.IDevice.listUdids(IDevice.java:136)
    at com.bugvm.compiler.target.ios.IOSTarget.createIOSDevLauncher(IOSTarget.java:262)
    at com.bugvm.compiler.target.ios.IOSTarget.createLauncher(IOSTarget.java:152)
    at com.bugvm.compiler.target.AbstractTarget.doLaunch(AbstractTarget.java:490)
    at com.bugvm.compiler.target.ios.IOSTarget.doLaunch(IOSTarget.java:602)
    at com.bugvm.compiler.target.AbstractTarget.launch(AbstractTarget.java:486)
    at com.bugvm.compiler.AppCompiler.launchAsync(AppCompiler.java:827)
    at com.bugvm.idea.running.BugVmRunProfileState.executeRun(BugVmRunProfileState.java:65)
    at com.bugvm.idea.running.BugVmRunProfileState.startProcess(BugVmRunProfileState.java:109)
    at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
    at com.bugvm.idea.running.BugVmRunner.doExecute(BugVmRunner.java:79)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
    at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:367)
    at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:144)
    at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:334)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:662)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:397)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

[WARNING] warning: no debug symbols in executable (-arch armv7)`

I push my sample to https://github.com/igorushko/libgdxBugVm

I can run on sumulator, i can create IPA and upload it to app store, but i can't run test build on device - it is critical for the development

i try arm64 it does not affect

i try iPhone 5 and iPhone 6p

thread https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bugvm/tIl4NCJYiEM/6kRQ8KV-AAAJ

**Comment by ibinti** [comment]
I am unable to reproduce this issue.
Your sample runs on my iPhone 5.

BTW, it appears that your Signing Identity and Provisioning Profile do not look good.
Refer to Apple documentation on how to set them correctly, typically with the Xcode.

**Comment by ibinti** [comment]
Even though a couple of people reported that they can run the app on the simulator but are unable to run the app on the device, it's weird that I can install to my iPhone and the app runs on my device.
I am having difficulty in reproducing the issue. There must be something that I overlooked.

**Comment by igorushko** [comment]
try install all on clear environment (VM). i use last mac os. Probably on your workstation installed something that no other

**Comment by kadriengin** [comment]
yes @ibinti  i updated in build.gradle. The error is "[ERROR] Couldn't start application
java.lang.NoClassDefFoundError: Could not initialize class com.bugvm.libimobiledevice.binding.LibIMobileDeviceJNI"

https://github.com/bugvm/bugvm/issues/58

my build.gradle is 

`buildscript {

```
ext {
    appName = "pluto"
    gdxVersion = '1.9.2'
    bugVMVersion = '1.1.0-SNAPSHOT'
    box2DLightsVersion = '1.4'
    ashleyVersion = '1.7.0'
    aiVersion = '1.8.0'
}
repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
dependencies {
    classpath 'com.android.tools.build:gradle:1.2.3'
    classpath "com.bugvm:bugvm-gradle-plugin:$bugVMVersion"
}
```

}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

```
version = '1.0'


repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url "https://oss.sonatype.org/content/repositories/releases/" }
}
```

}

project(":ios") {
    apply plugin: "java"
    apply plugin: "bugvm"

```
dependencies {
    compile project(":core")
    compile "com.bugvm:bugvm-rt:$bugVMVersion"
    compile "com.bugvm:bugvm-cocoatouch:$bugVMVersion"
    compile "com.bugvm:bugvm-libgdx:$bugVMVersion"

   // compile "com.badlogicgames.gdx:gdx-backend-bugvm:$gdxVersion"
    //compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
}
```

}

project(":core") {
    apply plugin: "java"

```
dependencies {
    compile "com.badlogicgames.gdx:gdx:$gdxVersion"
}
```

}

tasks.eclipse.doLast {
    delete ".project"
}`

**Comment by ibinti** [comment]
Could you guys try the tutorial hello world example (http://bugvm.com/getting-started/)? Please report back to me if the sample runs on device with command line compiler.
This will help to isolate the issue from the compiler and the associated Maven/Gradle/IntelliJ IDEA plugins.
Thanks

**Comment by ibinti** [comment]
expired
