### ISSUE TITLE
Run app in simulator great works but real device [ERROR] Couldn't start application ?

### ISSUE THREAD

**Issue by kadriengin** [bugvm/bugvm#58]
Hi friends,

I want to thank you all for this project, last month i was building mu project to ios with robovm. But it died :( and for a week im trying to setup bugvm and i finished setup.

I run my app on ios simulator working well. But when i send it to real device it says " [ERROR] Couldn't start application". Full error is bottom of the message. Can you help about this error ?

i forgatten to say. Im using bugvm studio...

[ERROR] Couldn't start application
java.lang.NoClassDefFoundError: Could not initialize class com.bugvm.libimobiledevice.binding.LibIMobileDeviceJNI
    at com.bugvm.libimobiledevice.binding.StringArrayOut.<init>(StringArrayOut.java:44)
    at com.bugvm.libimobiledevice.IDevice.listUdids(IDevice.java:136)
    at com.bugvm.compiler.target.ios.IOSTarget.createIOSDevLauncher(IOSTarget.java:262)
    at com.bugvm.compiler.target.ios.IOSTarget.createLauncher(IOSTarget.java:152)
    at com.bugvm.compiler.target.AbstractTarget.doLaunch(AbstractTarget.java:490)
    at com.bugvm.compiler.target.ios.IOSTarget.doLaunch(IOSTarget.java:602)
    at com.bugvm.compiler.target.AbstractTarget.launch(AbstractTarget.java:486)
    at com.bugvm.compiler.AppCompiler.launchAsync(AppCompiler.java:827)
    at com.bugvm.idea.running.BugVmRunProfileState.executeRun(BugVmRunProfileState.java:65)
    at com.bugvm.idea.running.BugVmRunProfileState.startProcess(BugVmRunProfileState.java:109)
    at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
    at com.bugvm.idea.running.BugVmRunner.doExecute(BugVmRunner.java:79)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
    at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:367)
    at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:144)
    at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:334)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:662)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:397)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

[ERROR] while processing /Users/darcanli/.bugvm/cache/ios/thumbv7/release/Users/darcanli/.gradle/caches/modules-2/files-2.1/com.bugvm/bugvm-libgdx/1.1.0-SNAPSHOT/3b8e172abb1dfc6f0c86442245e55ea059f76b4f/bugvm-libgdx-1.1.0-SNAPSHOT.jar.extracted/META-INF/bugvm/ios/libs/libObjectAL.a(OALAction.o):
[WARNING] warning: /var/folders/b9/14_qh0188xs07m006s6gwqs80000gq/C/com.apple.DeveloperTools/7.3-7D175/Xcode/SharedPrecompiledHeaders/ObjectAL (iOS)-Prefix-bnerbqxptykhdwdivuprmrgpqhif/ObjectAL (iOS)-Prefix.pch.pch: No such file or directory

**Comment by ibinti** [comment]
similar to #55, #46

**Comment by ibinti** [comment]
Are you using libgdx?
If you use bugvm studio, did you change the bugvm version to 1.1.0-SNAPSHOT in build.gradle?
bugvm studio's built-in compiler version is 1.0.6.

> [ERROR] while processing /Users/darcanli/.bugvm/cache/ios/thumbv7/release/Users/darcanli/.gradle/caches/modules-2/files-2.1/com.bugvm/bugvm-libgdx/1.1.0-SNAPSHOT/3b8e172abb1dfc6f0c86442245e55ea059f76b4f/bugvm-libgdx-1.1.0-SNAPSHOT.jar.extracted/META-INF/bugvm/ios/libs/libObjectAL.a(OALAction.o):

**Comment by ibinti** [comment]
Please follow the issue #46 and join the discussion.
